# Generated by Django 5.1.2 on 2024-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_multiloginaccount_multilogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiloginaccount',
            name='multilogin_profile_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
